version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Java: 8, 11, 17
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "${VARIANT:-11-bullseye}"
        APP_NAME: ${APP_NAME:-myapp}
        WILDFLY_VER: "${WILDFLY_VER:-23.0.2.Final}"

    volumes:
      - ..:/workspaces/${APP_NAME:-myapp}:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    env_file:
      - .env
