version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Java: 8, 11, 17
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "${VARIANT:-11-bullseye}"
        APP_NAME: ${APP_NAME:-myapp}
        WILDFLY_VER: "${WILDFLY_VER:-23.0.2.Final}"
        PG_DRIVER_VER: "${PG_DRIVER_VER:-42.7.4}"

    volumes:
      - ..:/workspaces/${APP_NAME:-myapp}:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    env_file:
      - .env

    depends_on:
      - db-postgres
      - db-mysql

  db-postgres:
    image: postgres:${PG_VERSION:-17}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/dbscript:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
      LANG: "C.UTF-8"
      TZ: "Asia/Tokyo"

  db-mysql:
    image: mysql:${MYSQL_VERSION:-8.4}
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/dbscript:/docker-entrypoint-initdb.d
    environment:
      # MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      LANG: "C.UTF-8"
      TZ: "Asia/Tokyo"

volumes:
  postgres-data: null
  mysql-data: null
